name: Auto Click on Document

on:
  push:
    branches:
      - main

jobs:
  auto-click:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2  # Update to the latest version that supports Node.js 16

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Run Auto Click Script
      run: python selesnium_script.py
